### PR TITLE
fix: ESCAPE proposal handling

### PR DESCRIPTION
**Pull request by ivelin**
- [x] Add handler for ESCAPE proposal processing
- [x] Test subgraph locally
- [x] Test subgraph on Goerli
- [x] Peer review 
- [ ] Deploy subgraph on hosted service for Goerli
- [ ] Get user feedback
- [ ] Deploy on mainnets: ETH L1, Arbitrum L2, etc.

### CODE REVIEW

**Comment by ivelin** [comment]
Update: 
Starting work on this issue:

https://discord.com/channels/923399898769018921/925091695677309059/1042853317748985917

https://github.com/SporosDAO/sweat-token/pull/174#issuecomment-1317455373

**Comment by ivelin** [comment]
@nerderlyne I think this PR fixes the issue. I tested manually on Goerli. Studio deployment [here](https://api.studio.thegraph.com/query/38831/ivelin-kalidao/0.0.5/graphql?query=query+MyQuery+%7B%0A++proposals%28%0A++++where%3A+%7Bdao_contains_nocase%3A+%220x3fcdf2b58ba93b1335766f01217b7ede7be61a0a%22%2C+escaped%3Atrue%7D%0A++%29+%7B%0A++++description%0A++++payloads%0A++++amounts%0A++++escaped%0A++++serial%0A++++status%0A++++sponsored%2C%0A++++creationTime%0A++++votingStarts%0A++++dao+%7B%0A++++++quorum%0A++++++votingPeriod%0A++++++supermajority%0A++++%7D%0A++%7D%0A%7D%0A++++%23%0A++++%23+Welcome+to+The+GraphiQL%0A++++%23%0A++++%23+GraphiQL+is+an+in-browser+tool+for+writing%2C+validating%2C+and%0A++++%23+testing+GraphQL+queries.%0A++++%23%0A++++%23+Type+queries+into+this+side+of+the+screen%2C+and+you+will+see+intelligent%0A++++%23+typeaheads+aware+of+the+current+GraphQL+type+schema+and+live+syntax+and%0A++++%23+validation+errors+highlighted+within+the+text.%0A++++%23%0A++++%23+GraphQL+queries+typically+start+with+a+%22%7B%22+character.+Lines+that+start%0A++++%23+with+a+%23+are+ignored.%0A++++%23%0A++++%23+An+example+GraphQL+query+might+look+like%3A%0A++++%23%0A++++%23+++++%7B%0A++++%23+++++++field%28arg%3A+%22value%22%29+%7B%0A++++%23+++++++++subField%0A++++%23+++++++%7D%0A++++%23+++++%7D%0A++++%23%0A++++%23+Keyboard+shortcuts%3A%0A++++%23%0A++++%23++Prettify+Query%3A++Shift-Ctrl-P+%28or+press+the+prettify+button+above%29%0A++++%23%0A++++%23+++++Merge+Query%3A++Shift-Ctrl-M+%28or+press+the+merge+button+above%29%0A++++%23%0A++++%23+++++++Run+Query%3A++Ctrl-Enter+%28or+press+the+play+button+above%29%0A++++%23%0A++++%23+++Auto+Complete%3A++Ctrl-Space+%28or+just+start+typing%29%0A++++%23%0A++)


Notice the new `escaped` attribute.

[Kali frontend](https://app.kali.gg/daos/5/0x3fcdf2b58ba93b1335766f01217b7ede7be61a0a) for this test DAO on Goerli.
[Sporos frontend](https://dev--sporosdaoapp-dev.netlify.app/dao/chain/5/address/0x3fcdf2b58ba93b1335766f01217b7ede7be61a0a/proposals/) for the same DAO.

Please let me know what you think. 🙏🏼

**Review by nerderlyne — CHANGES_REQUESTED** [review]
Small typo at 74 on README, looks good otherwise 

also getProposalIdBySerial helper in dao helpers file would be nice for consistency 

also sporos link seems broken rn
Screenshot 2022-12-01 at 6 20 57 PM

**Comment by ivelin** [comment]
@nerderlyne update:

> Small typo at 74 on README, looks good otherwise

fixed 

> also getProposalIdBySerial helper in dao helpers file would be nice for consistency

moved

Deployed update to studio playground. Dev test url [here](https://api.studio.thegraph.com/query/38831/ivelin-kalidao/0.0.6/graphql?query=query+MyQuery+%7B%0A++proposals%28%0A++++where%3A+%7Bdao_contains_nocase%3A+%220x3fcdf2b58ba93b1335766f01217b7ede7be61a0a%22%2C+escaped%3Atrue%7D%0A++%29+%7B%0A++++description%0A++++payloads%0A++++amounts%0A++++escaped%0A++++serial%0A++++status%0A++++sponsored%2C%0A++++creationTime%0A++++votingStarts%0A++++dao+%7B%0A++++++quorum%0A++++++votingPeriod%0A++++++supermajority%0A++++%7D%0A++%7D%0A%7D%0A++++%23%0A++++%23+Welcome+to+The+GraphiQL%0A++++%23%0A++++%23+GraphiQL+is+an+in-browser+tool+for+writing%2C+validating%2C+and%0A++++%23+testing+GraphQL+queries.%0A++++%23%0A++++%23+Type+queries+into+this+side+of+the+screen%2C+and+you+will+see+intelligent%0A++++%23+typeaheads+aware+of+the+current+GraphQL+type+schema+and+live+syntax+and%0A++++%23+validation+errors+highlighted+within+the+text.%0A++++%23%0A++++%23+GraphQL+queries+typically+start+with+a+%22%7B%22+character.+Lines+that+start%0A++++%23+with+a+%23+are+ignored.%0A++++%23%0A++++%23+An+example+GraphQL+query+might+look+like%3A%0A++++%23%0A++++%23+++++%7B%0A++++%23+++++++field%28arg%3A+%22value%22%29+%7B%0A++++%23+++++++++subField%0A++++%23+++++++%7D%0A++++%23+++++%7D%0A++++%23%0A++++%23+Keyboard+shortcuts%3A%0A++++%23%0A++++%23++Prettify+Query%3A++Shift-Ctrl-P+%28or+press+the+prettify+button+above%29%0A++++%23%0A++++%23+++++Merge+Query%3A++Shift-Ctrl-M+%28or+press+the+merge+button+above%29%0A++++%23%0A++++%23+++++++Run+Query%3A++Ctrl-Enter+%28or+press+the+play+button+above%29%0A++++%23%0A++++%23+++Auto+Complete%3A++Ctrl-Space+%28or+just+start+typing%29%0A++++%23%0A++).

> also sporos link seems broken rn 

Yes, others reported the same issue. Looks like the dev sandbox deployments of the front end hosting service Netlify has occasionally inconsistent availability. You can check the [latest preview deployment](https://deploy-preview-182--sporosdaoapp-dev.netlify.app/) for the related frontend [patch PR](https://github.com/SporosDAO/sweat-token/pull/182) . Note that the front end PR is dependent on pushing this subgraph change to Goerli hosting server for testing (and later to Arbitrum, etc. for prod).

I tried to test the front end PR with studio dev url for testing, but dev studio's URL won't let apps use fetch with graphql query POST. Only allows interactive mode with graphql query as a GET parameter and returns HTML instead of JSON.

**Pull request merged**
